{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "352580b8",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'tensorflow_federated'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[6], line 4\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mnumpy\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mnp\u001b[39;00m\n\u001b[0;32m      3\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mtensorflow\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mtf\u001b[39;00m\n\u001b[1;32m----> 4\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mtensorflow_federated\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mtff\u001b[39;00m\n\u001b[0;32m      5\u001b[0m np\u001b[38;5;241m.\u001b[39mrandom\u001b[38;5;241m.\u001b[39mseed(\u001b[38;5;241m0\u001b[39m)\n\u001b[0;32m      6\u001b[0m tff\u001b[38;5;241m.\u001b[39mfederated_computation(\u001b[38;5;28;01mlambda\u001b[39;00m: \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mHello, World!\u001b[39m\u001b[38;5;124m'\u001b[39m)()\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'tensorflow_federated'"
     ]
    }
   ],
   "source": [
    "import collections\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "import tensorflow_federated as tff\n",
    "np.random.seed(0)\n",
    "tff.federated_computation(lambda: 'Hello, World!')()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a0f41a79",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  Preparing metadata (pyproject.toml) did not run successfully.\n",
      "  exit code: 1\n",
      "  \n",
      "  [275 lines of output]\n",
      "  setup.py:67: RuntimeWarning: NumPy 1.19.5 may not yet support Python 3.10.\n",
      "    warnings.warn(\n",
      "  Running from numpy source directory.\n",
      "  setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates\n",
      "    run_build = parse_setuppy_commands()\n",
      "  Processing numpy/random\\_bounded_integers.pxd.in\n",
      "  Processing numpy/random\\bit_generator.pyx\n",
      "  Processing numpy/random\\mtrand.pyx\n",
      "  Processing numpy/random\\_bounded_integers.pyx.in\n",
      "  Processing numpy/random\\_common.pyx\n",
      "  Processing numpy/random\\_generator.pyx\n",
      "  Processing numpy/random\\_mt19937.pyx\n",
      "  Processing numpy/random\\_pcg64.pyx\n",
      "  Processing numpy/random\\_philox.pyx\n",
      "  Processing numpy/random\\_sfc64.pyx\n",
      "  Cythonizing sources\n",
      "  blas_opt_info:\n",
      "  blas_mkl_info:\n",
      "  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "  customize MSVCCompiler\n",
      "    libraries mkl_rt not found in ['C:\\\\Users\\\\shaif\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\libs', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\Library\\\\lib']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  blis_info:\n",
      "    libraries blis not found in ['C:\\\\Users\\\\shaif\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\libs', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\Library\\\\lib']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  openblas_info:\n",
      "    libraries openblas not found in ['C:\\\\Users\\\\shaif\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\libs', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\Library\\\\lib']\n",
      "  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'\n",
      "  customize GnuFCompiler\n",
      "  Could not locate executable g77\n",
      "  Could not locate executable f77\n",
      "  customize IntelVisualFCompiler\n",
      "  Could not locate executable ifort\n",
      "  Could not locate executable ifl\n",
      "  customize AbsoftFCompiler\n",
      "  Could not locate executable f90\n",
      "  customize CompaqVisualFCompiler\n",
      "  Could not locate executable DF\n",
      "  customize IntelItaniumVisualFCompiler\n",
      "  Could not locate executable efl\n",
      "  customize Gnu95FCompiler\n",
      "  Could not locate executable gfortran\n",
      "  Could not locate executable f95\n",
      "  customize G95FCompiler\n",
      "  Could not locate executable g95\n",
      "  customize IntelEM64VisualFCompiler\n",
      "  customize IntelEM64TFCompiler\n",
      "  Could not locate executable efort\n",
      "  Could not locate executable efc\n",
      "  customize PGroupFlangCompiler\n",
      "  Could not locate executable flang\n",
      "  don't know how to compile Fortran code on platform 'nt'\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  atlas_3_10_blas_threads_info:\n",
      "  Setting PTATLAS=ATLAS\n",
      "    libraries tatlas not found in ['C:\\\\Users\\\\shaif\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\libs', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\Library\\\\lib']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  atlas_3_10_blas_info:\n",
      "    libraries satlas not found in ['C:\\\\Users\\\\shaif\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\libs', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\Library\\\\lib']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  atlas_blas_threads_info:\n",
      "  Setting PTATLAS=ATLAS\n",
      "    libraries ptf77blas,ptcblas,atlas not found in ['C:\\\\Users\\\\shaif\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\libs', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\Library\\\\lib']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  atlas_blas_info:\n",
      "    libraries f77blas,cblas,atlas not found in ['C:\\\\Users\\\\shaif\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\libs', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\Library\\\\lib']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  accelerate_info:\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\system_info.py:1914: UserWarning:\n",
      "      Optimized (vendor) Blas libraries are not found.\n",
      "      Falls back to netlib Blas library which has worse performance.\n",
      "      A better performance should be easily gained by switching\n",
      "      Blas library.\n",
      "    if self._calc_info(blas):\n",
      "  blas_info:\n",
      "    libraries blas not found in ['C:\\\\Users\\\\shaif\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\libs', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\Library\\\\lib']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\system_info.py:1914: UserWarning:\n",
      "      Blas (http://www.netlib.org/blas/) libraries not found.\n",
      "      Directories to search for the libraries can be specified in the\n",
      "      numpy/distutils/site.cfg file (section [blas]) or by setting\n",
      "      the BLAS environment variable.\n",
      "    if self._calc_info(blas):\n",
      "  blas_src_info:\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\system_info.py:1914: UserWarning:\n",
      "      Blas (http://www.netlib.org/blas/) sources not found.\n",
      "      Directories to search for the sources can be specified in the\n",
      "      numpy/distutils/site.cfg file (section [blas_src]) or by setting\n",
      "      the BLAS_SRC environment variable.\n",
      "    if self._calc_info(blas):\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  non-existing path in 'numpy\\\\distutils': 'site.cfg'\n",
      "  lapack_opt_info:\n",
      "  lapack_mkl_info:\n",
      "    libraries mkl_rt not found in ['C:\\\\Users\\\\shaif\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\libs', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\Library\\\\lib']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  openblas_lapack_info:\n",
      "    libraries openblas not found in ['C:\\\\Users\\\\shaif\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\libs', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\Library\\\\lib']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  openblas_clapack_info:\n",
      "    libraries openblas,lapack not found in ['C:\\\\Users\\\\shaif\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\libs', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\Library\\\\lib']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  flame_info:\n",
      "    libraries flame not found in ['C:\\\\Users\\\\shaif\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\libs', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\Library\\\\lib']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  atlas_3_10_threads_info:\n",
      "  Setting PTATLAS=ATLAS\n",
      "    libraries lapack_atlas not found in C:\\Users\\shaif\\anaconda3\\lib\n",
      "    libraries tatlas,tatlas not found in C:\\Users\\shaif\\anaconda3\\lib\n",
      "    libraries lapack_atlas not found in C:\\\n",
      "    libraries tatlas,tatlas not found in C:\\\n",
      "    libraries lapack_atlas not found in C:\\Users\\shaif\\anaconda3\\libs\n",
      "    libraries tatlas,tatlas not found in C:\\Users\\shaif\\anaconda3\\libs\n",
      "    libraries lapack_atlas not found in C:\\Users\\shaif\\anaconda3\\Library\\lib\n",
      "    libraries tatlas,tatlas not found in C:\\Users\\shaif\\anaconda3\\Library\\lib\n",
      "  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  atlas_3_10_info:\n",
      "    libraries lapack_atlas not found in C:\\Users\\shaif\\anaconda3\\lib\n",
      "    libraries satlas,satlas not found in C:\\Users\\shaif\\anaconda3\\lib\n",
      "    libraries lapack_atlas not found in C:\\\n",
      "    libraries satlas,satlas not found in C:\\\n",
      "    libraries lapack_atlas not found in C:\\Users\\shaif\\anaconda3\\libs\n",
      "    libraries satlas,satlas not found in C:\\Users\\shaif\\anaconda3\\libs\n",
      "    libraries lapack_atlas not found in C:\\Users\\shaif\\anaconda3\\Library\\lib\n",
      "    libraries satlas,satlas not found in C:\\Users\\shaif\\anaconda3\\Library\\lib\n",
      "  <class 'numpy.distutils.system_info.atlas_3_10_info'>\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  atlas_threads_info:\n",
      "  Setting PTATLAS=ATLAS\n",
      "    libraries lapack_atlas not found in C:\\Users\\shaif\\anaconda3\\lib\n",
      "    libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\shaif\\anaconda3\\lib\n",
      "    libraries lapack_atlas not found in C:\\\n",
      "    libraries ptf77blas,ptcblas,atlas not found in C:\\\n",
      "    libraries lapack_atlas not found in C:\\Users\\shaif\\anaconda3\\libs\n",
      "    libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\shaif\\anaconda3\\libs\n",
      "    libraries lapack_atlas not found in C:\\Users\\shaif\\anaconda3\\Library\\lib\n",
      "    libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\shaif\\anaconda3\\Library\\lib\n",
      "  <class 'numpy.distutils.system_info.atlas_threads_info'>\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  atlas_info:\n",
      "    libraries lapack_atlas not found in C:\\Users\\shaif\\anaconda3\\lib\n",
      "    libraries f77blas,cblas,atlas not found in C:\\Users\\shaif\\anaconda3\\lib\n",
      "    libraries lapack_atlas not found in C:\\\n",
      "    libraries f77blas,cblas,atlas not found in C:\\\n",
      "    libraries lapack_atlas not found in C:\\Users\\shaif\\anaconda3\\libs\n",
      "    libraries f77blas,cblas,atlas not found in C:\\Users\\shaif\\anaconda3\\libs\n",
      "    libraries lapack_atlas not found in C:\\Users\\shaif\\anaconda3\\Library\\lib\n",
      "    libraries f77blas,cblas,atlas not found in C:\\Users\\shaif\\anaconda3\\Library\\lib\n",
      "  <class 'numpy.distutils.system_info.atlas_info'>\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  lapack_info:\n",
      "    libraries lapack not found in ['C:\\\\Users\\\\shaif\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\libs', 'C:\\\\Users\\\\shaif\\\\anaconda3\\\\Library\\\\lib']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\system_info.py:1748: UserWarning:\n",
      "      Lapack (http://www.netlib.org/lapack/) libraries not found.\n",
      "      Directories to search for the libraries can be specified in the\n",
      "      numpy/distutils/site.cfg file (section [lapack]) or by setting\n",
      "      the LAPACK environment variable.\n",
      "    return getattr(self, '_calc_info_{}'.format(name))()\n",
      "  lapack_src_info:\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\system_info.py:1748: UserWarning:\n",
      "      Lapack (http://www.netlib.org/lapack/) sources not found.\n",
      "      Directories to search for the sources can be specified in the\n",
      "      numpy/distutils/site.cfg file (section [lapack_src]) or by setting\n",
      "      the LAPACK_SRC environment variable.\n",
      "    return getattr(self, '_calc_info_{}'.format(name))()\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  numpy_linalg_lapack_lite:\n",
      "    FOUND:\n",
      "      language = c\n",
      "      define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]\n",
      "  \n",
      "  C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\dist.py:275: UserWarning: Unknown distribution option: 'define_macros'\n",
      "    warnings.warn(msg)\n",
      "  running dist_info\n",
      "  running build_src\n",
      "  build_src\n",
      "  building py_modules sources\n",
      "  creating build\n",
      "  creating build\\src.win-amd64-3.10\n",
      "  creating build\\src.win-amd64-3.10\\numpy\n",
      "  creating build\\src.win-amd64-3.10\\numpy\\distutils\n",
      "  building library \"npymath\" sources\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\shaif\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 351, in <module>\n",
      "      main()\n",
      "    File \"C:\\Users\\shaif\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 333, in main\n",
      "      json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "    File \"C:\\Users\\shaif\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 152, in prepare_metadata_for_build_wheel\n",
      "      return hook(metadata_directory, config_settings)\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 157, in prepare_metadata_for_build_wheel\n",
      "      self.run_setup()\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 248, in run_setup\n",
      "      super(_BuildMetaLegacyBackend,\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 142, in run_setup\n",
      "      exec(compile(code, __file__, 'exec'), locals())\n",
      "    File \"setup.py\", line 508, in <module>\n",
      "      setup_package()\n",
      "    File \"setup.py\", line 500, in setup_package\n",
      "      setup(**metadata)\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\core.py\", line 169, in setup\n",
      "      return old_setup(**new_attr)\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\__init__.py\", line 165, in setup\n",
      "      return distutils.core.setup(**attrs)\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\core.py\", line 148, in setup\n",
      "      dist.run_commands()\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 967, in run_commands\n",
      "      self.run_command(cmd)\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 986, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\command\\dist_info.py\", line 31, in run\n",
      "      egg_info.run()\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\command\\egg_info.py\", line 24, in run\n",
      "      self.run_command(\"build_src\")\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 313, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 986, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\command\\build_src.py\", line 144, in run\n",
      "      self.build_sources()\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\command\\build_src.py\", line 155, in build_sources\n",
      "      self.build_library_sources(*libname_info)\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\command\\build_src.py\", line 288, in build_library_sources\n",
      "      sources = self.generate_sources(sources, (lib_name, build_info))\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\command\\build_src.py\", line 378, in generate_sources\n",
      "      source = func(extension, build_dir)\n",
      "    File \"numpy\\core\\setup.py\", line 658, in get_mathlib_info\n",
      "      st = config_cmd.try_link('int main(void) { return 0;}')\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\command\\config.py\", line 243, in try_link\n",
      "      self._link(body, headers, include_dirs,\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\command\\config.py\", line 162, in _link\n",
      "      return self._wrap_method(old_config._link, lang,\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\command\\config.py\", line 96, in _wrap_method\n",
      "      ret = mth(*((self,)+args))\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\command\\config.py\", line 137, in _link\n",
      "      (src, obj) = self._compile(body, headers, include_dirs, lang)\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\command\\config.py\", line 105, in _compile\n",
      "      src, obj = self._wrap_method(old_config._compile, lang,\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\command\\config.py\", line 96, in _wrap_method\n",
      "      ret = mth(*((self,)+args))\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\command\\config.py\", line 132, in _compile\n",
      "      self.compiler.compile([src], include_dirs=include_dirs)\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\_msvccompiler.py\", line 401, in compile\n",
      "      self.spawn(args)\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-build-env-4pjrxgz7\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\_msvccompiler.py\", line 505, in spawn\n",
      "      return super().spawn(cmd, env=env)\n",
      "    File \"C:\\Users\\shaif\\AppData\\Local\\Temp\\pip-install-4ph62qke\\numpy_ee2e763b64214d59a708f9d44a5d92c0\\numpy\\distutils\\ccompiler.py\", line 90, in <lambda>\n",
      "      m = lambda self, *args, **kw: func(self, *args, **kw)\n",
      "  TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'\n",
      "  [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "error: metadata-generation-failed\n",
      "\n",
      "Encountered error while generating package metadata.\n",
      "\n",
      "See above for output.\n",
      "\n",
      "note: This is an issue with the package mentioned above, not pip.\n",
      "hint: See above for details.\n"
     ]
    }
   ],
   "source": [
    "pip install --quiet --upgrade tensorflow-federated"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eea7c2f1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "de0d4e6b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b4f6e262",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f8a8d7b3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dd7c5e24",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f6909f7f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7dcad28d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9f7e8037",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e31a14a7",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "97dcb75d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b0212a3f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eded6117",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "54d77fca",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5a317577",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1038f3d0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "12e33a66",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7d05bbd2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "02505c05",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ab265429",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "276728c1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1bdaad45",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c10884ca",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "76ac8db8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d5042cbb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7786498b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
